services:
     testapi:
       build:
         context: .
         dockerfile: Dockerfile
       ports:
         - "1000:1000"
       container_name: c_testapi
       deploy:
        resources:
          limits:
            cpus: '2.0'
            memory: 4G
          reservations:
            memory: 2G